name: deploy in environment using secret
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: PROD
    steps:
      - name: deploy
        run: echo ${{ secrets.PROD_DEPLOYMENT_SECRET }}
      # This command is just an example to show your secret being printed
