name: deploy in environment using secret
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Commit to trigger'
        # Default value if no value is explicitly provided
        default: 'latest'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  deployment_to_TEST:
    name: Test deployment
    runs-on: ubuntu-latest
    environment: 
      name: TEST
    steps:
      - name: deploy
        run: echo ${{ secrets.TEST_SECRET_VALUE }} > secrethomework_TEST.txt
      # This command is just an example to show your secret being printed
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload secret artifact
          path: secrethomework_TEST.txt
  deployment_to_PROD:
    needs: deployment_to_TEST
    name: PROD deployment
    runs-on: ubuntu-latest
    environment: 
      name: PROD
    steps:
      - name: deploy
        run: echo ${{ secrets.PROD_DEPLOYMENT_SECRET }} > secrethomework.txt
      # This command is just an example to show your secret being printed
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload secret artifact
          path: secrethomework.txt
        
