name: Scala CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: mvn -e gatling:test -D"gatling.simulationClass=computerdatabase.BasicSimulation"
